### ISSUE TITLE
Add Semantic Release

### ISSUE THREAD

**Issue by devopsmariocom** [wc-catalogue/blaze-elements#104]
https://github.com/atlassian/lerna-semantic-release

**Comment by Hotell** [comment]
what about this https://github.com/material-components/material-components-web/tree/master/scripts

**Comment by Hotell** [comment]
oh wow that atlassian fork looks great. this is a killer https://github.com/atlassian/cz-lerna-changelog

**Comment by Hotell** [comment]
Closed by #197
