### ISSUE TITLE
packaging: distribute declaration files

### ISSUE THREAD

**Issue by devopsmariocom** [wc-catalogue/blaze-elements#126]
```json
  "compilerOptions": {
    // @TODO
    // "declaration": true,
    // "declarationDir": "lib"
  }
```

**Comment by Hotell** [comment]
This is not sufficient unfortunately. We need to provide custom machinery how to output declaration files, webpack ts-loader doesn't help us :-/ so probably we would need to add custom task ( like after  build ) to generate those via `tsc` and copy them to appropriate places.

**Comment by devopsmariocom** [comment]
We need to fix type definitions first for each package.

**Comment by devopsmariocom** [comment]
We need either support this https://github.com/s-panferov/awesome-typescript-loader/pull/136 or run tsc manually during build process maybe using this https://github.com/1337programming/webpack-shell-plugin

**Comment by devopsmariocom** [comment]
Closed in #252

**Comment by Hotell** [comment]
So how was this resolved pls?

you said:

> We need either support this s-panferov/awesome-typescript-loader#136 or run tsc manually during build process maybe using this https://github.com/1337programming/webpack-shell-plugin

But in that PR none of proposed solutions is applied.

So I guess it's resolved by adding `declaration` + `declarationDir` to root `tsconfig.json` so when webpack runs it just runs `tsc` under the hood which emits the definitions.

Correct me if I wrong.

Also pls next time hit tht **Close and comment** button when closing issues manually

thx

**Comment by Hotell** [comment]
Any answer would be great
