### ISSUE TITLE
implement <bl-calendar>

### ISSUE THREAD

**Issue by hopkins-tk** [wc-catalogue/blaze-elements#16]
http://blazecss.com/components/calendars/

This may later be used in Date Picker & Date Time Picker.

However **Calendar** component should be plain calendar so that it can be used independently.

**Comment by davidrus** [comment]
@Hotell @hopkins-tk please take a look to this [new branch](https://github.com/wc-catalogue/blaze-elements/tree/davidrus/calendar/packages/calendar) and let me know what do you think about it?

**Comment by Hotell** [comment]
can you pls create a PR with WIP and add reviewers ? ;) I like to see diffs . dekuji

**Comment by davidrus** [comment]
NP, (neni zas)
