### ISSUE TITLE
refactor: bl-tag should create own CE namespace for Input

### ISSUE THREAD

**Issue by Hotell** [wc-catalogue/blaze-elements#171]
**Current behavior**

We are directly importing `Input` which is registered as `bl-input`. This behaviour will produce errors for consumers of both `tag/index-with-deps.js` `button/index-with-deps.js` because it will try to register `bl-button` twice.

**Expected behavior**

We have to namespace our `Input` with custom name scoped to tag package

**Comment by hopkins-tk** [comment]
@davidrus please also make sure to add dependency on `Input` and use import as `@blaze-elements/input`.
