### ISSUE TITLE
build: toolbelt templates

### ISSUE THREAD

**Issue by Hotell** [wc-catalogue/blaze-elements#180]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => You can submit support request here, but we preffer to chat about it realtime at our [ngParty slack](https://ngparty.herokuapp.com/)
```

**Current behavior**

Everytime we run toolbelt for generating templates it will override existing one, which will remove all dependencies that current package had...

**Expected behavior**

It should take into account every package.json dependencies and leave them as they are ( it should change only common config )

**Comment by hopkins-tk** [comment]
Another related question - maybe more generic.

What are all the things that we want to override and what not?
