### ISSUE TITLE
refactor: namespace components used within tag package

### ISSUE THREAD

**Issue by Hotell** [wc-catalogue/blaze-elements#191]
**Current behavior**

TagSelector uses internal Tag and Input which will lead in error, when user want's to use spearate packages of `bl-input` and `bl-tag`.

**Expected behavior**

Input and tag needst to be namespace and registration to customElements registry should be in barrel `index.ts`

Look at https://github.com/wc-catalogue/blaze-elements/tree/master/packages/calendar/components for more info

**Comment by hopkins-tk** [comment]
Isn't this duplicate of https://github.com/wc-catalogue/blaze-elements/issues/171?

**Comment by Hotell** [comment]
yes, my bad, thx !
