### ISSUE TITLE
refactor(alert): follow actual guideline

### ISSUE THREAD

**Issue by davidrus** [wc-catalogue/blaze-elements#243]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => You can submit support request here, but we preffer to chat about it realtime at our [ngParty slack](https://ngparty.herokuapp.com/)
```

**Current behavior**
Alert needs to be refactored

**Expected behavior**
Alert will be refactored.

**Comment by davidrus** [comment]
:)

**Comment by davidrus** [comment]
There is a problem with actual devstack or build because when I try to import button from package, I get an error:
```
Uncaught ReferenceError: skatejs is not defined
    at Object.t.a (index.min.js:1)
```

Do someone know where is a problem? @Hotell @hopkins-tk @elmariofredo

**Comment by devopsmariocom** [comment]
maybe you are loading npm module instead of lerna or something like that, please check your node_modules folder what button is there.

**Comment by davidrus** [comment]
The problem was in importing button from index not from Button.tsx as Raw Class. I need only register our custom bl-alert-button. But thanks :)

**Comment by devopsmariocom** [comment]
ahh ok make sense glad it's resolved 👍
