### ISSUE TITLE
Collapsible & Accordion not working in Safari

### ISSUE THREAD

**Issue by hopkins-tk** [wc-catalogue/blaze-elements#36]
Collapsible & Accordion are not working in Safari - they always open the first collapsible item on the page.

Reported by @elmariofredo.

**Comment by davidrus** [comment]
For me It works fine (safari v10.0.2)
![jan-02-2017 10-18-29](https://cloud.githubusercontent.com/assets/1128128/21586763/da49a454-d0d4-11e6-860e-7462cdc28495.gif)

**Comment by devopsmariocom** [comment]
yes this was fixed by https://github.com/wc-catalogue/blaze-elements/pull/38
