### ISSUE TITLE
Add Link

### ISSUE THREAD

**Issue by devopsmariocom** [wc-catalogue/blaze-elements#93]

**Comment by devopsmariocom** [comment]
closed by https://github.com/wc-catalogue/blaze-elements/issues/22

**Comment by davidrus** [comment]
I reopened this issue, because we discovered that blazecss adding ordered list via content in ::before at li element and we found some solution in this [branch](https://github.com/wc-catalogue/blaze-elements/tree/davidrus/lists/packages/list).

**Comment by davidrus** [comment]
If some of you have good mood and courage to finish it, please checkout that branch :).
TODO:
- unordered list (remove numbers)
- style numbers to have the same width for all items (1...100...1000)
